In [1]:
import numpy as np
import pandas as pd

In [33]:
df = pd.read_csv('cars.csv')

In [35]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [9]:
df.shape

(8128, 5)

In [37]:
# 1. Train Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['selling_price']), df['selling_price'], test_size=0.2, random_state=0)

X_train.shape, X_test.shape

((6502, 4), (1626, 4))

In [19]:
X_train.head()

         brand  km_driven    fuel         owner
3042   Hyundai      60000     LPG   First Owner
1520      Tata     150000  Diesel   Third Owner
2611   Hyundai     110000  Diesel  Second Owner
3544  Mahindra      28000  Diesel  Second Owner
4138    Maruti      15000  Petrol   First Owner

In [21]:
# 2. OnehotEncoding using pandas
pd.get_dummies(X_train, columns=['fuel','owner'])

,brand,km_driven,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
3042,Hyundai,60000,False,False,True,False,True,False,False,False,False
1520,Tata,150000,False,True,False,False,False,False,False,False,True
2611,Hyundai,110000,False,True,False,False,False,False,True,False,False
3544,Mahindra,28000,False,True,False,False,False,False,True,False,False
4138,Maruti,15000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
4931,Tata,70000,False,True,False,False,False,False,False,False,True
3264,Ford,100000,False,True,False,False,False,False,True,False,False
1653,Hyundai,90000,False,False,False,True,False,False,True,False,False
2607,Volkswagen,90000,False,True,False,False,True,False,False,False,False
2732,Hyundai,110000,False,False,False,True,True,False,False,False,False

In [23]:
# To avoid multicollinearity, we need to remove first column of every category
pd.get_dummies(data=X_train, columns=['fuel','owner'], drop_first=True)

,brand,km_driven,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
3042,Hyundai,60000,False,True,False,False,False,False,False
1520,Tata,150000,True,False,False,False,False,False,True
2611,Hyundai,110000,True,False,False,False,True,False,False
3544,Mahindra,28000,True,False,False,False,True,False,False
4138,Maruti,15000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...
4931,Tata,70000,True,False,False,False,False,False,True
3264,Ford,100000,True,False,False,False,True,False,False
1653,Hyundai,90000,False,False,True,False,True,False,False
2607,Volkswagen,90000,True,False,False,False,False,False,False
2732,Hyundai,110000,False,False,True,False,False,False,False

In [91]:
# OnehotEncoding using scikit-learn
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32)

In [93]:
ohe.fit(X_train[['fuel','owner']])

OneHotEncoder(drop='first', dtype=<class 'numpy.int32'>, sparse_output=False)

In [95]:
X_train

           brand  km_driven    fuel         owner
3042     Hyundai      60000     LPG   First Owner
1520        Tata     150000  Diesel   Third Owner
2611     Hyundai     110000  Diesel  Second Owner
3544    Mahindra      28000  Diesel  Second Owner
4138      Maruti      15000  Petrol   First Owner
...          ...        ...     ...           ...
4931        Tata      70000  Diesel   Third Owner
3264        Ford     100000  Diesel  Second Owner
1653     Hyundai      90000  Petrol  Second Owner
2607  Volkswagen      90000  Diesel   First Owner
2732     Hyundai     110000  Petrol   First Owner

[6502 rows x 4 columns]

In [97]:
X_train_new = ohe.transform(X_train[['fuel','owner']])
X_test_new = ohe.transform(X_test[['fuel','owner']])

In [99]:
X_train_new

array([[0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]])

In [101]:
np.hstack((X_train[['brand','km_driven']].values, X_train_new)).shape

(6502, 9)